# ParsersConfig config
sv-company:
  active: false
  url: https://sv-company.ru/
  class: App\Parser\Spider\Spider
  items_list_url: https://sv-company.ru/avtozapchasti/avtozapchasti-b-u/
  url_pattern: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/.+/
  url_pattern_detail: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/[^\/]+\/$/
  items_list_selector: .//a
  selectors:
      title:
        value: './/h1[@class="product__title"]'
      brand:
        value: './/nav/ul[@class="breadcrumbs page__breadcrumbs"]/li[3]/a'
      model:
        value: './/nav/ul[@class="breadcrumbs page__breadcrumbs"]/li[4]/a'
      img:
        value: './/img[@class="gallery__img"][1]/@src'
        isRelativePath: True
      price:
        value: './/span[@class="product__price"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      isAvalable:
        value: './/tbody/tr[td="Статус"]/td[2]'

razbor-nt:
  active: false
  url: http://razbor-nt.ru/
  class: App\Parser\Spider\Spider
  items_list_url: http://razbor-nt.ru/
  items_list_selector: .//a
  url_pattern: /http:\/\/razbor-nt.ru\/[^\?\/]+\//
  url_pattern_detail: /http:\/\/razbor-nt.ru\/[^\/]+\/[^\/]+\/[^\/]+\/[^\/]+.html$/
  request_dalay: 350
  selectors:
      title:
        value: '//*[@id="content"]/div[@class="b1c-good"]/h1'
      brand:
        value: '//*[@id="content"]/div/div[@class="breadcrumb-style"]/a[2]'
      model:
        value: '//*[@id="content"]/div/div[@class="breadcrumb-style"]/a[3]'
      img:
        value: '//*[@id="image"]/@src'
        isRelativePath: False
      price:
        value: '//div[@class="price"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'

разборкасокол:
  active: false
  url: https://разборкасокол.рф/
  class: App\Parser\Spider\Spider
  items_list_url: https://разборкасокол.рф/
  items_list_selector: .//a
  url_pattern: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai((?!\/shiny\/|\/vw\/).)+\//
  url_pattern_detail: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai\/[^\/]+\/[^\/]+.html$/
  max_depth: 7
  selectors:
      title:
        value: '//*[@id="content"]/h1'
      brand:
        value: '//div[@class="breadcrumb"]/a[2]'
      model:
        value: '//*[@id="content"]/h1'
        need_parse_model_by_brand: true
      description:
        value: '//div[@class="opisanie_tovar"]'
      img:
        value: '//*[@id="image"]/@src'
        isRelativePath: False
      price:
        value: '//div[@class="price"][1]'
        preg_replace:
          pattern: '/\\t+/'
          replace: ' '
        regexp: '/\d\s?\d+(\s?\d+)?/'

autoinfo51:
  active: false
  url: http://www.autoinfo51.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://www.autoinfo51.ru
  items_list_selector: .//a
  url_pattern: /^http:\/\/www.autoinfo51.ru\/catalog\/.+/
  url_pattern_detail: /^http:\/\/www.autoinfo51.ru\/catalog\/[\d]+\/[\d]+\/$/
  max_depth: 4
  request_dalay: 500
  selectors:
      row:
        value: '//table[@class="catalog"]/tr[position() >= 2]'
      brand_model:
        value: '//td[2]'
        need_parse_model_and_brand: true
      title:
        value: '//td[3]'
      description:
        value: '//td[5]'
      price:
        value: '//td[6]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//td[7]/a/@href'
        isRelativePath: False

raz45:
  active: true
  url: http://raz45.ru
  class: App\Parser\Spider\Spider
#  items_list_url: http://raz45.ru
  items_list_url: http://raz45.ru/automotiveparts/1056
  items_list_selector: .//a
  url_pattern: /http:\/\/raz45.ru\/automotiveparts\/[^\?]+$/
  url_pattern_detail: /^http:\/\/raz45.ru\/automotiveparts\/[^\?][0-9]+$/
  max_depth: 4
  request_dalay: 200
  selectors:
      acticul:
        value: '//div[@class="field field-name-field-cataloguenumbers field-type-field-collection field-label-above"]/div/span'
      brand_model:
        value: '//h1[@id="page-title"]'
        need_parse_model_and_brand: true
      title:
        value: '//div[@class="field field-name-field-gr-automotiveparts field-type-taxonomy-term-reference field-label-above"]/div/span'
#        composition: '#acticul# #title# #model# #car_body_code# #brand#'
      price:
        value: '//td[@class="component-total"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//span[@class="field-item even"][1]/a/img/@src'

avito-razorbor-voroneg:
  active: false
  url: https://www.avito.ru/razorbor-voroneg/rossiya/zapchasti_i_aksessuary?view=list
  class: App\Parser\Spider\Spider
  items_list_url: https://www.avito.ru/razorbor-voroneg/rossiya/zapchasti_i_aksessuary?view=list
  items_list_selector: .//a
  url_pattern: /https:\/\/www.avito.ru\/(razorbor-voroneg\/rossiya\/zapchasti_i_aksessuary\?p=[0-9]{1,2}|voronezh\/zapchasti_i_aksessuary\/.+)/
  url_pattern_detail: /https:\/\/www.avito.ru\/voronezh\/zapchasti_i_aksessuary\/.+/
  max_depth: 10
  request_dalay: 1500
  selectors:
      brand_model:
        value: '//span[@class="title-info-title-text"]'
        need_parse_model_and_brand: true
      title:
        value: '//span[@class="title-info-title-text"]'
      price:
        value: '//*[@id="price-value"]/span'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//span[@class="gallery-img-cover"]/img/@src'

relines:
  active: true
  url: http://relines.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://relines.ru
  items_list_selector: .//a
  url_pattern: /^http:\/\/relines.ru\/(catalog\/[^\?]+\/|products\/[^\?]+)/
  url_pattern_detail: /^http:\/\/relines.ru\/products\/.+/
  max_depth: 5
  request_dalay: 500
  selectors:
      brand_model:
        value: '//h3[@class="b-product__cars__i"][1]'
        need_parse_model_and_brand: true
      title:
        value: '//h2[@class="b-product__t"]'
      price:
        value: '//p[@class="b-product__pNb__p"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//img[@class="pic main"][1]/@src'
        isRelativePath: True

autopart-sib:
  active: true
  url: http://autopart-sib.ru/
  class: App\Parser\Spider\Spider
  items_list_url: http://autopart-sib.ru/?tree_id=0&shid=off&uid=&l=&part=sh&maker_id=&model_id=&shassi=&caruid=
  items_list_selector: .//a
  url_pattern: /^http:\/\/autopart-sib.ru\//
  url_pattern_detail: /^http:\/\/autopart-sib.ru\/p[0-9]+.html/
  max_depth: 5
  request_dalay: 300
  selectors:
      brand:
        value: '//*[@id="car_charts"]/tr/td[span="Производитель авто:"]/text()'
      model:
        value: '//*[@id="car_charts"]/tr/td[span="Модель авто:"]/text()'
      title:
        value: '//*[@id="car_charts"]/tr/td[span="Наименование:"]/h1'
      description:
        value: '//*[@id="car_name"]'
      price:
        value: '//*[@id="car_charts"]/tr/td/span/span[@class="red"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//*[@id="car_table"]/tr[last()]/td[last()]/table/tr/td/a/img/@src'

autotown55:
  active: true
  url: https://autotown55.ru/
  class: App\Parser\Spider\Spider
  items_list_url: https://autotown55.ru/catalog/
  items_list_selector: .//a
  url_pattern: /^https:\/\/autotown55.ru\/catalog\//
  url_pattern_detail: /^https:\/\/autotown55.ru\/catalog\/.+\.html/
  max_depth: 5
  request_dalay: 300
  selectors:
      brand:
        value: '//div[@class="auto_card_inf"]/p[normalize-space(text())="Марка"]/span'
      model:
        value: '//div[@class="auto_card_inf"]/p[normalize-space(text())="Модель"]/span'
      title:
        value: '//div[@class="auto_breadcrumbs"][1]/span'
      price:
        value: '//span[@class="cost"][1]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//div[@class="one_slide_inside"][1]/a[@class="fancybox"]/img/@src'
        isRelativePath: True

razbor72:
  active: true
  url: http://razbor72.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://razbor72.ru/zap
  items_list_selector: .//a
  url_pattern: /^http:\/\/razbor72.ru\//
  url_pattern_detail: /^http:\/\/razbor72.ru\/product\/.+/
  max_depth: 4
  request_dalay: 200
  selectors:
      brand_model:
        value: '//div[@class="main"][1]/h1'
        need_parse_model_and_brand: true
      title:
        value: '//div[@class="main"][1]/h1'
      price:
        value: '//p[@class="price"][1]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//img[@class="big_img"]/@src'
        isRelativePath: True

razbormashin:
  active: true
  url: http://razbormashin.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://razbormashin.ru/avtozapchasti
  items_list_selector: .//a
  url_pattern: /^http:\/\/razbormashin.ru\/avtozapchasti\//
  url_pattern_detail: /^http:\/\/razbormashin.ru\/avtozapchasti\/[^\/]+\/[^\/]+\/[^\/]+\/[^\/]+.html/
  max_depth: 4
  request_dalay: 200
  selectors:
      brand:
        value: '//div[@class="product-detail-property"][div[1]="Производитель"]/div[2]'
      model:
        value: '//div[@class="product-detail-property product-detail-property_space"][div[1]="Модель"]/div[2]'
      title:
        value: '//h1[@class="product-detail__title"]'
      description:
        value: '//div[@class="product-detail__description-text"]'
      isAvalable:
        value: '//div[@class="product-detail-property product-detail-property_space"][div[1]="Наличие"]/div[2]'
      price:
        value: '//div[@class="product-detail__price-value"][1]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//*[@id="msGallery"]/div/a[1]/@href'
        isRelativePath: True

avtodriver:
  active: true
  url: https://avtodriver.com
  class: App\Parser\Spider\Spider
  items_list_url: https://avtodriver.com
  items_list_selector: .//a
  url_pattern: /^https:\/\/avtodriver.com\//
  url_pattern_detail: /^https:\/\/avtodriver.com\/[^\/]+\/[^\/]+\//
  max_depth: 4
  request_dalay: 200
  selectors:
      brand:
        value: '//h1[@class="caption"][1]'
        need_parse_brand: True
      model:
        value: '//*[@id="c_d"]/p[normalize-space(text())="Устанавливается на модель:"]/b'
      title:
        value: '//h1[@class="caption"][1]'
      description:
        value: '//p[@class="toppropelemdescr"]'
        optional: True
      isAvalable:
        value: '//div[@class="b-catalog__avaliability"]'
      price:
        value: '//div[@class="b-price__element b-price-value"][1]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//section[@class="regular slider"]/a[1]/img/@src'
        isRelativePath: True

caroptics:
  active: true
  url: https://www.caroptics.ru
  class: App\Parser\Spider\Spider
  items_list_url: https://www.caroptics.ru/product/
  items_list_selector: .//a
  url_pattern: /^https:\/\/www.caroptics.ru\//
  url_pattern_detail: /^https:\/\/www.caroptics.ru\/product\/[^\/]+\//
  max_depth: 6
  request_dalay: 200
  selectors:
      brand:
        value: '//*[@id="breadcrumbs"]/div[2]/a'
      model:
        value: '//*[@id="breadcrumbs"]/div[3]/a'
      title:
        value: '//h1[@itemprop="name"][1]'
      isAvalable:
        value: '//div[@class="in_stock"]'
      price:
        value: '//meta[@itemprop="price"]/@content'
      img:
        value: '//div[@class="product_images"]/div[@class="big"]/a/@href'
        isRelativePath: True

45razbor:
  active: true
  url: http://www.45razbor.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://www.45razbor.ru/index.php/nashi-rekvizity
  items_list_selector: .//a
  url_pattern: /^http:\/\/www.45razbor.ru\//
  url_pattern_detail: /^http:\/\/www.45razbor.ru\/index.php\/nashi-rekvizity\/product\/view\/[0-9]+\/[0-9]+$/
  max_depth: 6
  request_dalay: 200
  selectors:
      brand_model:
        value: '//div[@class="jshop productfull"]/form/h1/text()'
        need_parse_model_and_brand: true
      title:
        value: '//div[@class="jshop productfull"]/form/h1/text()'
      price:
        value: '//*[@id="block_price"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//span[@id="list_product_image_middle"]/a/img/@src'

car22:
  active: true
  url: https://car22.ru
  class: App\Parser\Spider\Spider
  items_list_url: https://car22.ru/katalog-zapchastej/
  items_list_selector: .//a
  url_pattern: /^https:\/\/car22.ru\/katalog-zapchastej\//
  url_pattern_detail: /^https:\/\/car22.ru\/katalog-zapchastej\/[^\/]+\/.+\/$/
  max_depth: 5
  request_dalay: 200
  selectors:
      brand_model:
        value: '//h1[@itemprop="name"][1]'
        need_parse_model_and_brand: true
      title:
        value: '//h1[@itemprop="name"][1]'
      price:
        value: '//meta[@itemprop="price"]/@content'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//a[@itemprop="image"][1]/img/@src'
        isRelativePath: True

nilina-auto:
  active: true
  url: https://nilina-auto.ru
  class: App\Parser\Spider\Spider
  items_list_url: https://nilina-auto.ru
  items_list_selector: .//a
  url_pattern: /^https:\/\/nilina-auto.ru\//
  url_pattern_detail: /^https:\/\/nilina-auto\.ru\/[^\/]+\.html$/
  max_depth: 5
  request_dalay: 200
  selectors:
      brand:
        value: '//table[@class="b-product-info"]/tr[td[normalize-space(text())="Производитель"]]/td[2]'
      model:
        value: '//h1[@itemprop="name"][1]'
        need_parse_model_by_brand: true
      title:
        value: '//h1[@itemprop="name"][1]'
      price:
        value: '//span[@itemprop="price"]/@content'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//*[@class="b-product"]/div[1]/div[@class="b-centered-image b-product__image"]/img/@src'
        isRelativePath: True


